#pragma once

#include "driver/gpio.h"

#ifdef LLBEACON_BOARD_ATOMS3_LITE
#define LLBEACON_BUTTON_GPIO GPIO_NUM_41
#define LLBEACON_RGB_LED_GPIO GPIO_NUM_35
#define LLBEACON_RGB_LED_COUNT 4
#define LLBEACON_IR_GPIO GPIO_NUM_4
#define LLBEACON_I2C_SDA_GPIO GPIO_NUM_1
#define LLBEACON_I2C_SCL_GPIO GPIO_NUM_2
#define LLBEACON_VOICE_I2C_SDA_GPIO GPIO_NUM_38
#define LLBEACON_VOICE_I2C_SCL_GPIO GPIO_NUM_39
#define LLBEACON_I2S_BCK_GPIO GPIO_NUM_8
#define LLBEACON_I2S_WS_GPIO GPIO_NUM_6
#define LLBEACON_I2S_DOUT_GPIO GPIO_NUM_5
#define LLBEACON_I2S_DIN_GPIO GPIO_NUM_7
#elif defined(LLBEACON_BOARD_ATOM_LITE)
#define LLBEACON_BUTTON_GPIO GPIO_NUM_39
#define LLBEACON_RGB_LED_GPIO GPIO_NUM_27
#define LLBEACON_RGB_LED_COUNT 1
#define LLBEACON_IR_GPIO GPIO_NUM_12
#define LLBEACON_I2C_SDA_GPIO GPIO_NUM_25
#define LLBEACON_I2C_SCL_GPIO GPIO_NUM_21
#define LLBEACON_VOICE_I2C_SDA_GPIO GPIO_NUM_25
#define LLBEACON_VOICE_I2C_SCL_GPIO GPIO_NUM_21
#define LLBEACON_I2S_BCK_GPIO GPIO_NUM_33
#define LLBEACON_I2S_WS_GPIO GPIO_NUM_19
#define LLBEACON_I2S_DOUT_GPIO GPIO_NUM_22
#define LLBEACON_I2S_DIN_GPIO GPIO_NUM_23
#else
#error "Select exactly one supported LLBeacon board target."
#endif
